version: "3.9"

services:
  grafana:
    image: grafana/grafana-oss
    environment:
      GF_INSTALL_IMAGE_RENDERER_PLUGIN: true
    ports:
      - "8030:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - graphite
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - '2003:2003'

volumes:
  grafana_data:
    external: false
