POST http://localhost:8089/
Content-Type: application/json

{
    "stratId": 0,
    "stratName": "HELLO",
    "symbol": "GBPUSD",
    "direction": "SELL",
    "timestamp": "2019-08-27T09:56:00Z"
}
###
POST http://localhost:8089/
Content-Type: application/json

{}

