
# Valid Open Sell alert
POST http://localhost:8089/alert
Content-Type: application/json

{
    "id": 0,
    "name": "HELLO",
    "symbol": "FXCM:GBPUSD",
    "interval": 15,
    "direction": "SELL",
    "price": 1.1,
    "timestamp": "2019-08-27T09:56:00Z"
}
###

# Valid Open Buy alert
POST http://localhost:8089/alert
Content-Type: application/json

{
    "id": 0,
    "name": "HELLO",
    "symbol": "FXCM:GBPUSD",
    "interval": 15,
    "direction": "buy",
    "price": 1.1,
    "timestamp": "2019-08-27T09:56:00Z"
}
###

# Valid Close long alert
POST http://localhost:8089/alert
Content-Type: application/json

{
    "id": 0,
    "name": "HELLO",
    "symbol": "FXCM:GBPUSD",
    "interval": 15,
    "direction": "Close entry(s) order long",
    "price": 1.1,
    "timestamp": "2019-08-27T09:56:00Z"
}
###

# Valid Close short alert
POST http://localhost:8089/alert
Content-Type: application/json

{
    "id": 0,
    "name": "HELLO",
    "symbol": "FXCM:GBPUSD",
    "interval": 15,
    "direction": "Close entry(s) order short",
    "price": 1.1,
    "timestamp": "2019-08-27T09:56:00Z"
}
###

# Invalid close alert "Cloxe" instead of "Close"
POST http://localhost:8089/alert
Content-Type: application/json

{
    "id": 0,
    "name": "HELLO",
    "symbol": "FXCM:GBPUSD",
    "interval": 15,
    "direction": "Cloxe entry(s) order short",
    "timestamp": "2019-08-27T09:56:00Z"
}
###

# Invalid Sell alert - missing "interval"
POST http://localhost:8089/alert
Content-Type: application/json

{
    "id": 0,
    "name": "HELLO",
    "symbol": "FXCM:GBPUSD",
    "direction": "SELL",
    "timestamp": "2019-08-27T09:56:00Z"
}
###

# Invalid alert - missing content
POST http://localhost:8089/alert
Content-Type: application/json

{}
###

# Valid heartbeat request
GET http://localhost:8089/
###

