POST http://localhost:8089/carbon-alert
Content-Type: application/json

{
    "stratId": 0,
    "stratName": "EMARSI",
    "symbol": "FXCM:GBPUSD",
    "interval": 15,
    "direction": "SELL",
    "timestamp": "2022-09-27T20:24:00Z"
}
###

POST http://localhost:8089/carbon-alert
Content-Type: application/json

{
    "stratId": 0,
    "stratName": "EMARSI",
    "symbol": "FXCM:GBPUSD",
    "direction": "SELL",
    "timestamp": "2019-08-27T09:56:00Z"
}
###

POST http://localhost:8089/carbon-alert
Content-Type: application/json

{}

